name: "GinBlog"
mode: "dev"
version: "v0.0.1"
start_time: "2024-10-09"
machine_id: 1
port: 8808

auth:
  jwt_expire: 1200

log:
  level: "info"
  filename: "GinBlog.log"
  max_size: 200
  max_age: 30
  max_backups: 2
mysql:
  host: 127.0.0.1
  port: 3306
  user: "root"
  password: "123"
  dbname: "ginblog"
  max_open_conns: 150
  max_idle_conns: 20
redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 0
  pool_size: 20
  min_idle_conns: 5